import type { Metadata } from "next";
import { ToastContainer } from "react-toastify";
import "./globals.css";
import useLocalStorage from "@/shared/hooks/useLocalStorage";
import { RouterProvider } from "@/contexts/routerContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
        />
      </head>

      <body>
        <ToastContainer />
        <RouterProvider>{children}</RouterProvider>
      </body>
    </html>
  );
}
